version: '3.8'
services:
  backend:
    build: ./backend
    portss: 
      - "5000:5000"
    environment:
      -FLASK_ENV=development
    depends_on:
      - db

  frontend:
    buold: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  db:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: